env:
  global:
    - PROJECT_NAME=mi-bici
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    - secure: "XVFPYwGdwTdLk99opDAWgUKAuDta4EhuzM9km31CFVaxWFaFoqUYqz6q926NX9ZENjtmQGttdrknTh5E+M4vd+MlRLTawl7FBL4QdByDmbCN3m0zyBWLc56a/3UypsuU4P3e0UHPTvID9UXa/8Dp2J/YDdmzdilpWfc1lwUGG8bqdzu64iCpsRK4aNzFg4D6eDpHHvgKmgr6vvk0R9prsrgVtasj969BHxYgRxHnXFRKKQwseGaQcjgylphzb3qbFX8Q9wSLmRs3c9ZF2cYQn3EGtONTkfKZhdikZwLN13AIXT2LLnsyJJkJTH3maK9kQ4QxB9UoBoCK/rHrJJIDrm9gLLvyvhgwsniYWtEt4tjRRP0On9jZ0FQRLcrnolrKqcBAtJGRLbF/p7bOi6D5TBuWdMX16TiNKSL1JZKbHxD0hLdi/sDzwSm3N3Fg3baTBR2eoQojtjAGDcrXzQbN71EYnfP6t48SevB9zmsCDkHDWzDycWiftYNUeTdrhgMg6jxrLgbhr+lLi8h/6GWUZx7avhPyjPJTXytTiRFJjk13M2MnCLlzHqlT93Pbwh0rvdio6fh3VvRcxcX5ZSolqKhiYx6kdwNZJL2TLvKSVxytxfq0PXR1jkA5LZU4iHdL1Zl20xFz6gsTVfWvTptScOgik0eQKfpwzBhT+FO4QgI="
    # beta SHA256-af7507b9411c78ff3df1efd621fbcb9ec9ab7057af1aa1e543dbca6a9c4020f0
    - secure: "eoeDdrz0KpuFDZlxEK2JelNdgtMFh8BiCMAaSC0m864/cqCSXDywC2vzgBKVWcqPH64MOxafMzzO4HKfxVlolzNzDOtjuMQfzx3AjY1V5Q+i1KEJ+i08CQbrqMlUSRm65CiqZIPiflfe7B8Wkl1KorzTvdEukump4ztdKPmrNDsiJduX8Y2p9jBf7sMEEBdZO2TOb3Ym8y4ddfgctHPxVnhDpNa9CaJ99hYUAd28ScTN+ix7sNMq8RO25dxrFf1t7U/Vezr9JYH5KF2YUqVuIX2CKSCuk3AtAJxepRUGIgaRg28HrIxdSF5yBLf27hItDpoQ0HGwn0PIXaCm8xXwf2BkzgnU9cjQPKI1j9dsFHBuTmvg639gDDfP51l0KyYvEpq4AZRCOJ3wkck1UbhpJa6+urTVoYz6AJVTDdSsU/bDjLm/XMvH4hZ8Z8JRdBjNxi9t1AcoHlKpWbb/CJbvYSuP2DplfKFP8gpEz3PSo+MA6M0/pqoQvtX6w95lHofLkbbj2bOmnf45AC3XpI0w7g2J1/ktQRYC5mVdNz7KX+5YGFOToCbjGZa0itWiO7bX+ZV3VbyIIJ+pvwcfF+uEDO/IRocdkSq0k+d1XRNBbe9MZ1qEXDa8MilrDyc5Hrh7myDZMg4qFwaTjRGQGKOxjVJbIJVFmSXsOOj2w9J0EAY="
script:
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass -v 3.4.23 --no-ri --no-rdoc
  - ./public/site/templates/koi.sh -p -f
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta
after_deploy:
  - './cleanup.py "${!GIT_FTP_URL_BRANCH}"'
